---
- name: install nfs-kernel-server
  apt:
    name: nfs-kernel-server
    state: present

- name: create exports dir
  file:
    path: /exports
    state: directory

- name: configure nfs-kernel-server
  copy:
    src: exports
    dest: /etc/
  notify: restart nfs-kernel-server
