---
- name: download iso to /tmp
  get_url:
    url: http://releases.ubuntu.com/focal/ubuntu-20.04.1-live-server-amd64.iso
    dest: /tmp/

- name: install 7z
  apt:
    name: p7zip-full
    state: present

- name: extract to web server
  shell: 7z x /tmp/ubuntu-20.04.1-live-server-amd64.iso -o/var/www/focal/
  args:
    creates: /var/www/focal/

- name: copy cloud-config file
  copy:
    src: cloud-config
    dest: /var/www/focal/

- name: chown dir
  file:
    path: /var/www/focal/
    owner: www-data
    recurse: yes

- name: create boot entry
  copy:
    src: script.ipxe
    dest: /tftpboot/

